
CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text UNIQUE;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userProfileUrl text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteFontSize text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteTheme text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS customerProfileId text;

CREATE TABLE IF NOT EXISTS Team();
ALTER TABLE Team ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS region text UNIQUE;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS abbreviation text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS teamId text UNIQUE;

CREATE TABLE IF NOT EXISTS Guesser();
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS name text UNIQUE;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS guesserId text UNIQUE;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS description text;

CREATE TABLE IF NOT EXISTS Championship();
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS finalFour text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS guesserId text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS freeThrowsMade integer;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS game1Winner text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS game1Loser text;

CREATE TABLE IF NOT EXISTS FinalFour();
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS eliteEight text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS guesserId text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS freeThrowsMade integer;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game1Winner text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game1Loser text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game2Winner text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game2Loser text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS championship text;

CREATE TABLE IF NOT EXISTS EliteEight();
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS sweetSixteen text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS guesserId text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS freeThrowsMade integer;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS southGame1Winner text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS southGame1Loser text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS westGame1Winner text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS westGame1Loser text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS eastGame1Winner text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS eastGame1Loser text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS midwestGame1Winner text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS midwestGame1Loser text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS finalFour text;

CREATE TABLE IF NOT EXISTS SweetSixteen();
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS guesserId text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS freeThrowsMade integer;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame1Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame1Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame2Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame2Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame1Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame1Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame2Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame2Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame1Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame1Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame2Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame2Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame1Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame1Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame2Winner text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame2Loser text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eliteEight text;

DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'championship_finalfour_finalfour_fkey') THEN ALTER TABLE Championship ADD CONSTRAINT championship_finalfour_finalfour_fkey FOREIGN KEY(finalFour) REFERENCES FinalFour(bracketId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'championship_guesserid_guesser_fkey') THEN ALTER TABLE Championship ADD CONSTRAINT championship_guesserid_guesser_fkey FOREIGN KEY(guesserId) REFERENCES Guesser(guesserId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'championship_game1winner_team_fkey') THEN ALTER TABLE Championship ADD CONSTRAINT championship_game1winner_team_fkey FOREIGN KEY(game1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'championship_game1loser_team_fkey') THEN ALTER TABLE Championship ADD CONSTRAINT championship_game1loser_team_fkey FOREIGN KEY(game1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'finalfour_eliteeight_eliteeight_fkey') THEN ALTER TABLE FinalFour ADD CONSTRAINT finalfour_eliteeight_eliteeight_fkey FOREIGN KEY(eliteEight) REFERENCES EliteEight(bracketId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'finalfour_guesserid_guesser_fkey') THEN ALTER TABLE FinalFour ADD CONSTRAINT finalfour_guesserid_guesser_fkey FOREIGN KEY(guesserId) REFERENCES Guesser(guesserId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'finalfour_game1winner_team_fkey') THEN ALTER TABLE FinalFour ADD CONSTRAINT finalfour_game1winner_team_fkey FOREIGN KEY(game1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'finalfour_game1loser_team_fkey') THEN ALTER TABLE FinalFour ADD CONSTRAINT finalfour_game1loser_team_fkey FOREIGN KEY(game1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'finalfour_game2winner_team_fkey') THEN ALTER TABLE FinalFour ADD CONSTRAINT finalfour_game2winner_team_fkey FOREIGN KEY(game2Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'finalfour_game2loser_team_fkey') THEN ALTER TABLE FinalFour ADD CONSTRAINT finalfour_game2loser_team_fkey FOREIGN KEY(game2Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'finalfour_championship_championship_fkey') THEN ALTER TABLE FinalFour ADD CONSTRAINT finalfour_championship_championship_fkey FOREIGN KEY(championship) REFERENCES Championship(bracketId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_sweetsixteen_sweetsixteen_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_sweetsixteen_sweetsixteen_fkey FOREIGN KEY(sweetSixteen) REFERENCES SweetSixteen(bracketId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_guesserid_guesser_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_guesserid_guesser_fkey FOREIGN KEY(guesserId) REFERENCES Guesser(guesserId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_southgame1winner_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_southgame1winner_team_fkey FOREIGN KEY(southGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_southgame1loser_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_southgame1loser_team_fkey FOREIGN KEY(southGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_westgame1winner_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_westgame1winner_team_fkey FOREIGN KEY(westGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_westgame1loser_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_westgame1loser_team_fkey FOREIGN KEY(westGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_eastgame1winner_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_eastgame1winner_team_fkey FOREIGN KEY(eastGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_eastgame1loser_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_eastgame1loser_team_fkey FOREIGN KEY(eastGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_midwestgame1winner_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_midwestgame1winner_team_fkey FOREIGN KEY(midwestGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_midwestgame1loser_team_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_midwestgame1loser_team_fkey FOREIGN KEY(midwestGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'eliteeight_finalfour_finalfour_fkey') THEN ALTER TABLE EliteEight ADD CONSTRAINT eliteeight_finalfour_finalfour_fkey FOREIGN KEY(finalFour) REFERENCES FinalFour(bracketId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_guesserid_guesser_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_guesserid_guesser_fkey FOREIGN KEY(guesserId) REFERENCES Guesser(guesserId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_southgame1winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_southgame1winner_team_fkey FOREIGN KEY(southGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_southgame1loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_southgame1loser_team_fkey FOREIGN KEY(southGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_southgame2winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_southgame2winner_team_fkey FOREIGN KEY(southGame2Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_southgame2loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_southgame2loser_team_fkey FOREIGN KEY(southGame2Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_westgame1winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_westgame1winner_team_fkey FOREIGN KEY(westGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_westgame1loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_westgame1loser_team_fkey FOREIGN KEY(westGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_westgame2winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_westgame2winner_team_fkey FOREIGN KEY(westGame2Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_westgame2loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_westgame2loser_team_fkey FOREIGN KEY(westGame2Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_eastgame1winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_eastgame1winner_team_fkey FOREIGN KEY(eastGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_eastgame1loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_eastgame1loser_team_fkey FOREIGN KEY(eastGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_eastgame2winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_eastgame2winner_team_fkey FOREIGN KEY(eastGame2Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_eastgame2loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_eastgame2loser_team_fkey FOREIGN KEY(eastGame2Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_midwestgame1winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_midwestgame1winner_team_fkey FOREIGN KEY(midwestGame1Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_midwestgame1loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_midwestgame1loser_team_fkey FOREIGN KEY(midwestGame1Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_midwestgame2winner_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_midwestgame2winner_team_fkey FOREIGN KEY(midwestGame2Winner) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_midwestgame2loser_team_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_midwestgame2loser_team_fkey FOREIGN KEY(midwestGame2Loser) REFERENCES Team(teamId); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT constraint_name FROM information_schema.constraint_column_usage WHERE table_schema = 'public' AND constraint_name = 'sweetsixteen_eliteeight_eliteeight_fkey') THEN ALTER TABLE SweetSixteen ADD CONSTRAINT sweetsixteen_eliteeight_eliteeight_fkey FOREIGN KEY(eliteEight) REFERENCES EliteEight(bracketId); END IF; END $$;
