
CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text UNIQUE;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userProfileUrl text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteFontSize text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteTheme text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS customerProfileId text;

CREATE TABLE IF NOT EXISTS Team();
ALTER TABLE Team ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS region text UNIQUE;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS abbreviation text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE Team ADD COLUMN IF NOT EXISTS teamId text UNIQUE;

CREATE TABLE IF NOT EXISTS Guesser();
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS name text UNIQUE;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS guesserId text UNIQUE;
ALTER TABLE Guesser ADD COLUMN IF NOT EXISTS description text;

CREATE TABLE IF NOT EXISTS Championship();
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS finalFour text references FinalFour(championship);
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS guesserId text references Guesser(guesserId);
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS game1Winner text references Team(teamId);
ALTER TABLE Championship ADD COLUMN IF NOT EXISTS game1Loser text references Team(teamId);

CREATE TABLE IF NOT EXISTS FinalFour();
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS eliteEight text references EliteEight(finalFour);
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS guesserId text references Guesser(guesserId);
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game1Winner text references Team(teamId);
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game1Loser text references Team(teamId);
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game2Winner text references Team(teamId);
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS game2Loser text references Team(teamId);
ALTER TABLE FinalFour ADD COLUMN IF NOT EXISTS championship text references Championship(finalFour);

CREATE TABLE IF NOT EXISTS EliteEight();
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS sweetSixteen text references SweetSixteen(eliteEight);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS guesserId text references Guesser(guesserId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS southGame1Winner text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS southGame1Loser text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS westGame1Winner text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS westGame1Loser text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS eastGame1Winner text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS eastGame1Loser text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS midwestGame1Winner text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS midwestGame1Loser text references Team(teamId);
ALTER TABLE EliteEight ADD COLUMN IF NOT EXISTS finalFour text references FinalFour(eliteEight);

CREATE TABLE IF NOT EXISTS SweetSixteen();
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS editPage text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS userPage text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS download text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS guesserId text references Guesser(guesserId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS bracketId text UNIQUE;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame1Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame1Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame2Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS southGame2Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame1Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame1Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame2Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS westGame2Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame1Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame1Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame2Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eastGame2Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame1Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame1Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame2Winner text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS midwestGame2Loser text references Team(teamId);
ALTER TABLE SweetSixteen ADD COLUMN IF NOT EXISTS eliteEight text references EliteEight(sweetSixteen);
