DROP TABLE SiteUser CASCADE;
DROP TABLE Team CASCADE;
DROP TABLE Guesser CASCADE;
DROP TABLE Championship CASCADE;
DROP TABLE FinalFour CASCADE;
DROP TABLE EliteEight CASCADE;
DROP TABLE SweetSixteen CASCADE;
